title: Xuan Cheng's Homepage
page-top-title: Xuan Cheng[程选]
top-section-bg-text: Psychology
home-subtitle: Xuan Cheng&ensp;|&ensp;程选
copyright-text: '&copy; Xuan Cheng 2024-2025. All Rights Reserved.'
